version: '2'
services:
    test_database:
        container_name: database
        image: flocurry/mysql5.7:0.0.2
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASES=laravel
            - MYSL_HOST=192.168.0.7  
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
        volumes:
            - ~/www/mysql_volumes/:/var/lib/mysql
        # Adresse IP statique pour le container
        networks:
            dock_net:
              ipv4_address: 192.168.0.7
    test_php:
        container_name: php
        image: flocurry/php7:0.0.2
        volumes:
            - ~/www/laravel/:/var/www/html/
        # Su le même réseau que la base car les 2 containers doivent communiquer
        networks:
            dock_net:
              ipv4_address: 192.168.0.6
    test_web:
        container_name: apache
        image: flocurry/apache2:0.0.2
        ports:
            - 80:80
        environment:
            FPM_HOST: test_php:9000
        volumes:
            - ~/www/laravel/:/var/www/html/
        links:
            - test_php
        networks:
            dock_net:
              ipv4_address: 192.168.0.5
# Création d'un réseau
networks:
  dock_net:
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1